# Generated by Django 5.0.6 on 2024-07-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_docente_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='apellido',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='docente',
            name='email',
            field=models.EmailField(default='N/A', max_length=254),
        ),
        migrations.AddField(
            model_name='docente',
            name='telefono',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(default='N/A', max_length=254),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
